<?php
$listaLiberacao = json_decode($this->listaLiberacao());
$listaAprovacao = json_decode($this->listaAprovacao());
$countLiberacao = '';
$countAprovacao = '';
if ($_SESSION['nivel'] == 'gerente' ) {
  $countAprovacao = count($listaAprovacao);
  $countLiberacao = count($listaLiberacao);
}
?>
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand logomenu" href="/intranet">
      <img alt="Brand" src="../img/intranetmenu.png">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/pdr">
          <i class="fa fa-file-text"></i>
          Requisições
          </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/nova_rc">
          <i class="fa fa-plus-square-o"></i>
          Criar RC
          </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/liberar">
          <i class="fa fa-unlock">
            <?php 
            if ($countLiberacao > 0) {
              if ($countLiberacao > 10) {
                echo '<span class="badge badge-danger">'.$countLiberacao.'</span>';
              } else {
                echo '<span class="badge badge-warning">'.$countLiberacao.'</span>';
              }
            }
            ?>
          </i>
          Liberar RC
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/aprovar">
          <i class="fa fa-thumbs-o-up">
            <?php
            if ($countAprovacao > 0) {
              if ($countAprovacao > 10) {
                echo '<span class="badge badge-danger">'.$countAprovacao.'</span>';
              } else {
                echo '<span class="badge badge-warning">'.$countAprovacao.'</span>';
              }
            }
            ?>
          </i>
          Aprovar RC
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/provedores">
          <i class="fa fa-users">
          </i>
          Provedores
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/relatorios">
          <i class="fa fa-book" aria-hidden="true">
            <span class="badge badge-success">!</span>
          </i>
          Relatórios
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" data-toggle="modal" data-tt="tooltip" data-placement="right" title="Versão" data-target="#modalsobre">
          <i class="fa fa-info">
          </i>
          Sobre
        </a>
      </li>
      <!--li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-envelope-o">
            <span class="badge badge-primary">11</span>
          </i>
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li-->
    </ul>
    <ul class="navbar-nav mr-auto">
      <form class="form-inline" action="/pesquisar" method="POST" >
        <input class="form-control input-sm mr-sm-2" type="number" name="rc" placeholder="Pesquisar RC" aria-label="Search">
        <input type="hidden" name="pagina" value="1">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
      </form>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" data-toggle="modal" data-tt="tooltip" data-placement="right" title="SINCRONIZAR" data-target="#modalsincronizar">
          <i class="fa fa-cloud-download" aria-hidden="true">
          </i>
          Omie
        </a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="/sair">
            <i class="fa fa-share">
            </i>
            Sair
          </a>
      </li>
    </ul>
  </div>
</nav>
                                  <script src="ajax.js"></script>
<!----------------------------------------------------------------------------------------------------------------------------------------------INICIO MODAL SINCRONIZAR ------------------------------------------------------------------------------------------------------------------------------------------------->
<div class="modal fade" id="modalsincronizar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class='modal-header'>
        <h3 class='modal-title' id='exampleModalLongTitle'>
          SINCRONIZAÇÃO DE INFORMAÇÕES DO OMIE:
        </h3>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </div>
      <p class="text-success text-center">
          Os botões de sincronização são disparados automaticamente todos os dias à partir das 04:00hrs.
        </p>
      <div class="modal-body">
        <div class="container" id="carregando" style="display: none;">
          <img src="img/loading.gif" class="rounded mx-auto d-block">
          <h3 class="text-center">Sincronizando...</h3>
        </div>
        <div class="container" id="conteudo"></div>
        <div id="botaoProd">
          <div class="row container justify-content-center">
            <button type="button" class="btn-lg btn-primary" id="sincronizar">Sincronizar Produtos</button>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<button type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="right" title="Sincroniza os produtos e serviços cadastrados no Omie desde a última sincronização.">&nbsp?&nbsp</button>
          </div>
        </div>
        <div id="botaoPed">
          <div class="row container justify-content-center">
            <button type="button" class="btn-lg btn-primary" id="sincPedido">Sincronizar Requisições</button>&nbsp&nbsp
            <button type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="right" title="Sincroniza as requisições igualando com as informações no ERP Omie.">&nbsp?&nbsp</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-------------------------------------  FIM MODAL SINCRONIZAR ---------------------------------------->

<!------------------------------------------------------------------------------------------------------------------------------------------------------INICIO MODAL SOBRE ------------------------------------------------------------------------------------------------------------------------------------------------->
<div class="modal fade" id="modalsobre" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class='modal-header'>
        <h3 class='modal-title' id='exampleModalLongTitle'>
          SOBRE
        </h3>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-dark">
          <tr>
            <th scope="row">Software: </th>
            <th>PDR - Portal de Requisições</th>
          </tr>
          <tr>
            <th scope="row">Versão:  </th>
            <th>2.4</th>
          </tr>
          <tr>
            <th scope="row">Manual:  </th>
            <th><a href="IT-006_Portal de Requisições.pdf"  target="blank" >Acessar</a></th>
          </tr>
          <tr>
            <th scope="row">Suporte:</th>
            <th><a href="mailto:ti@aferitec.com.br?subject=Dúvida no PDR">ti@aferitec.com.br</a> <br> (19)9 9921-6546</th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
<!-------------------------------------  FIM MODAL SINCRONIZAR ---------------------------------------->