<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="cardd">
			<div class="card-header">
				<div class="row">
					<div class="col-7">
						<h3>Login Intranet</h3>
					</div>
					<div class="col-5">
						<img src="img/branco.png" class="img-fluid" alt="Responsive image">
					</div>
				</div>				
			</div>
			<div class="card-body">				
				<form method="post" action="/autenticar">
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="nome.sobrenome" name="conta">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="senha" name="senha">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Lembre-me
					</div>
					<div class="form-group">
						<input type="submit" value="Entrar" class="btn float-right login_btn">
					</div>
				</form>
				
					<div class='container'></div><hr>
				
			</div>
			<div class="card-footer">
				<?php
					if ($this->view->login == 'erro') {
				?>
				<div class="d-flex justify-content-center">
					<h3 class='text-danger'>Usuário ou senha inválido</h3>
				</div>
				<?php
					}
				?>
				<div class="d-flex justify-content-center links">
					Problemas ao entrar? &nbsp<a href="mailto:ti@aferitec.com.br">Ajuda</a>
				</div>				
			</div>
		</div>
	</div>
</div>

<!--template retirado de https://bootsnipp.com/snippets/vl4R7 -->