<div class="container">

	<div class="container">
		<div class="row">
			<div class="col-2"></div>
			<div class="col-8 text-center"><h4>CONTROLE DE ATIVIDADES HOME OFFICE</h4></div>
			<div class="col-2">
				<a class="nav-link" href="/intranet">
        	    	<i class="fa fa-share"></i>
        	    	Voltar
        	  	</a>
        	</div>
		</div>
	</div>

	<div class="row justify-content-center">

		<div class="col-md-3">
      	  	<div class="card mb-4 shadow-sm cartao">
      	  	    <div class="card-body">
      	  	      	<a href="/ho_user" style="text-decoration: none">
      	  	      		<img src="img/funcionario_ho.png" class="img-fluid" alt="Responsive image"><hr>
      	  	      		<h2 class="text-center">Entrar como Funcionário</h2>
      	  	      	</a>
      	  	    </div>
      	  	</div>
      	</div>
<?php if ($_SESSION['nivel'] != 'user') { ?>
		<div class="col-md-3">
      	  	<div class="card mb-4 shadow-sm cartao">
      	  	    <div class="card-body">
      	  	      	<a href="/ho_supervisor" style="text-decoration: none">
      	  	      		<img src="img/controle_ho.png" class="img-fluid" alt="Responsive image"><hr>
      	  	      		<h2 class="text-center">Entrar como Supervisor</h2>
      	  	      	</a>
      	  	    </div>
      	  	</div>
      	</div>
<?php } if ($_SESSION['nivel'] == 'gerente') { ?>
      	<div class="col-md-3">
      	  	<div class="card mb-4 shadow-sm cartao">
      	  	    <div class="card-body">
      	  	      	<a href="/ho_gerente" style="text-decoration: none">
      	  	      		<img src="img/analise_ho.png" class="img-fluid" alt="Responsive image"><hr>
      	  	      		<h2 class="text-center">Entrar como Gerente</h2>
      	  	      	</a>
      	  	    </div>
      	  	</div>
      	</div>
<?php } ?>
	</div>
</div>