<div class="container">
  	<div class="row">
        <div class="col-3 align-self-start">
          <h3 class="apresentacao"><?php echo $_SESSION['nome'];?></h3>
          <h3><?php echo $_SESSION['dpto']; ?></h3>
        </div>
  		<div class="col-6 align-self-center">
  			<h2 class="text-center titulao">intranet aferitec</h2>
  		</div>
  		<div class="col-3 align-self-end">
  			<a class="text-center exit" href="/sair">sair</a>
  		</div>
  	</div>
</div>
<br>
<div class="container">
	<div class="row">

      	<div class="col-md-4">
      	  <div class="card mb-4 shadow-sm cartao">
      	    <div class="card-body">
      	      <a href="https://aferitec.geiko.com.br/salesforce" target="blank" style="text-decoration: none">
      	      	<img src="img/vendas.png" class="img-fluid" alt="Responsive image"><hr>
      	      	<h2>Módulo Vendedor</h2>
      	      </a>
      	    </div>
      	  </div>
      	</div>

        <div class="col-md-4">
          <div class="card mb-4 shadow-sm cartao">
            <div class="card-body">
              <a href="https://aferitec.geiko.com.br/crm" target='blank' style="text-decoration: none">
              	<img src="img/crm.png" class="img-fluid" alt="Responsive image"><hr>
                <h2>Módulo Gerente</h2>
              </a>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card mb-4 shadow-sm cartao">
            <div class="card-body">
              <a href='https://geiko.com.br' target="blank" style='text-decoration: none'>
                    <img src="img/geikosite.png" class="img-fluid" alt="Responsive image"><hr>            
                    <h2>Site (chat)</h2>
              </a>
            </div>
          </div>
        </div>

    </div>
</div>