<html>
	<head>
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<!-- As 3 meta tags acima *devem* vir em primeiro lugar dentro do `head`; qualquer outro conteúdo deve vir *após* essas tags -->
    	<title>..:Intranet:..</title>

    	<!-- Bootstrap -->

    	<!--favicon-->
    	<link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon" /> 

    	<link href="css/bootstrap.min.css" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Staatliches" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Molengo" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Ubuntu+Condensed" rel="stylesheet">
    	<link rel="stylesheet" type="text/css" href="css/estilo.css">

    	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    	<script src="https://igorescobar.github.io/jQuery-Mask-Plugin/js/jquery.mask.min.js"></script>


    

   		<script language="JavaScript">
    
        	//função do purpose
        	$(function () {
        	$('[data-toggle="popover"]').popover()
        	})
    	</script>

		<link rel="stylesheet" href="/css/estilo.css" />

	</head>

	<body class="bg-light">
		<?= $this->content() ?>
	</body>

</html>